name:                haskell-code-obfuscator
version:             0.1.0.0
github:              "githubuser/haskell-code-obfuscator"
license:             BSD3
author:              "Maria Kuklina"
maintainer:          "mkdirwtf@gmail.com"
copyright:           "2020 Maria Kuklina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-code-obfuscator#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- ghc >= 8.8.4
- ghc-exactprint
- syb  >= 0.5
- ghc-paths
- ghc-source-gen

library:
  source-dirs: src

executables:
  haskell-code-obfuscator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-code-obfuscator

tests:
  haskell-code-obfuscator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-code-obfuscator
